### ISSUE TITLE
[h3mlib] Parsing: incomplete oa_type list  

### ISSUE THREAD

**Issue by Dergash** [potmdehex/homm3tools#13]
There are several OA types for a 'decorative' objects which is legit for map editor but missing from list at parse_oa_meta_type.c (for example, 202 which is 'volcano'). This cause conversion process to fail when input map contains such object. 

Done definition:
Conversion process should not fail when input map contains object with legit oa types.

Code: 
[https://github.com/potmdehex/homm3tools/blob/master/h3m/h3mlib/h3m_parsing/parse_oa_meta_type.c](url)

Note:
I attached a sample map which currently fails to convert
[OAParseFailDemo.zip](https://github.com/potmdehex/homm3tools/files/148950/OAParseFailDemo.zip)

**Comment by potmdehex** [comment]
See #14
