### ISSUE TITLE
[h3mlib] Conversion: Conflux heroes crash conversion

### ISSUE THREAD

**Issue by Dergash** [potmdehex/homm3tools#15]
When conflux heroes are present on the input map, next things occured: conversion fails if hero is an elementalist, or an output map are crashed when trying to customize a hero if it was a planewalker.

Done definition:
Conflux heroes should be replaced by random heroes during conversion.

**Comment by potmdehex** [comment]
@Dergash, to my knowledge this issue has been fixed in the past but may since have re-appeared. If I have time to prioritize it I will take a look.

Done definition as proposed.

**Comment by Dergash** [comment]
@potmdehex, I believe that there are two reasons behind the crash:
1. Currently if id is greater than 0x80 (where conflux heroes starts) and lesser than 0x90 (where special heroes starts) than we substract 0x80 from it. But, there is a hero class parameter, and if hero id not fall under its type hero pool than we got a crash. I.e, Passisa (planewalker, class 0x10, id 0x80) converted to Orrin (knight, class 0x00, id 0x00) is not valid. 
2. There is also a disturbing conversion in a map player's section. It seems that player section converter thinks that there is no conversion at all for expansion heroes and he should drop player to default 'No Player, No Town' type which also causes crash in some cases. Perphaps before #16 implemented we should make something like this in _convert_players function (convert.c):

``` c
#if 1
           // If hero is an expansion hero, simply remove it from here
            if (player_ext_out->e2.starting_hero_type >= 0x80
                || (player_ext_out->e2.starting_hero_face >= 0x80
                    && 0xFF != player_ext_out->e2.starting_hero_face)) {

                player_ext_out->e2.starting_hero_is_random = 1;

                // e2 -> e0
               /* player_ext_out->e0.starting_hero_is_random = 0;
                player_ext_out->e0.starting_hero_type = 0xFF;
                ctx_out->meta.player_ext_types[i] = 0;
                ext_size = sizeof(player->roe.u.e0);
                */
                break;
            }
#endif
```

Case 3 with 'Town and Player' type of this section should also be altered in a similiar way.

UPDATE: It's seems that actually there is a block for setting hero class ( entry_out->body.object_number) but it hits only when .def is match to conflux hero. At the time when control flow arrives, def is already replaced by red round AVWmrnd0.def. 
As done definition states that conflux heroes should be converted into random heroes at the moment, and as random hero seemengly counted as "no hero" for a player section, there is no need for changing _convert_players function.
