### ISSUE TITLE
[h3mlib] Town objects bug

### ISSUE THREAD

**Issue by radekmie** [potmdehex/homm3tools#26]
Hi, @potmdehex!

There's a problem with `object_names_hash` and/or `def_bodies_array` order:

```c
h3m_object_add(h3m, "Castle", &oa_index);      // 1311, OK
h3m_object_add(h3m, "Rampart", &oa_index);     // 1312, OK
h3m_object_add(h3m, "Tower", &oa_index);       // 1313, OK
h3m_object_add(h3m, "Inferno", &oa_index);     // 1314, OK
h3m_object_add(h3m, "Necropolis", &oa_index);  // 1315, OK
h3m_object_add(h3m, "Dungeon", &oa_index);     // 1316, OK
h3m_object_add(h3m, "Stronghold", &oa_index);  // 1318, should be 1319, results in Fortress
h3m_object_add(h3m, "Fortress", &oa_index);    // 102042, should be 1318, error
h3m_object_add(h3m, "Random Town", &oa_index); // 1317, OK
```

**Comment by potmdehex** [comment]
Thanks for the detailed report. Probably the easiest hack fix would be to change def_bodies_array order.

 If I get time to prioritize it at some point I will look into it.

**Comment by radekmie** [comment]
Changing `def_bodies_array` order will fix `Stronghold` case, but what with `Fortress`? If you'd give me an idea on how to change `object_names_hash`, I'd love to help.

**Comment by radekmie** [comment]
Workaround _(if you agree, I'll submit a PR)_:

```diff
-	return g[f0] + g[f1] + g[f2];
+	int result = g[f0] + g[f1] + g[f2];
+	if (result == 1318) // Stronghold workaround
+		return 1319;
+	if (result == 102042) // Fortress workaround
+		return 1318;
+
+	return result;
```

**Comment by potmdehex** [comment]
That's a hacky workaround but you can sumbit it as a PR and I will merge it after I test it. I would then add a comment explaining the underlying issue myself (trickier to solve, the hashes are generated by some old tools of mine which are not even in this repository and that I have not used or maintained for a very  long while).

**Comment by radekmie** [comment]
PR ready. If you want _(and it's possible obviously)_, I can try to help with these tools.

**Comment by potmdehex** [comment]
Fixed in #27. I might get back to you on those tools.

**Comment by potmdehex** [comment]
I got the old tools running so I could make a proper fix of the hash itself, as well as fix expansion objects such as "Bow of the Sharpshooter" which can now also be added with h3m_add_object as expected.
https://github.com/potmdehex/homm3tools/commit/921f5bbd84209ae93f9725747dcb80ffd2478796

Thanks for bringing light to the issue, @radekmie.

**Comment by radekmie** [comment]
Looks great!
