### ISSUE TITLE
Sadly not working...

### ISSUE THREAD

**Issue by XIIIFaces** [potmdehex/homm3tools#41]
I just found your tool and was so excited but saddly it doesn't work (anymore?)...
So first I had the problem that I dont't even have "h3maped.exe" it's just called "mapEditor.exe".
I tried downloading and putting the "old" one into the direction but then it just showed me that the dll's weren't on the right place. [This was all on Ubuntu 18.04] Since it's for Windows I then thought maybe I'm just doing copying wrong and used on Windows the .exe file to install the mod which led to basic crash directly at start.
Maybe you got some spare time for this :)
If not - no problem :)

**Comment by potmdehex** [comment]
I assume you are talking about HDE mod. It's made specifically for the latest version of HD Edition on Steam. What language and version are you using? Btw h3maped.exe is only for RMG Integration, no other features need it, so you could also use HDE mod without it if you just uncheck RMG in the HD Edition launcher.

**Comment by XIIIFaces** [comment]
Oh yes Hde 1.22 - and I'm using the most recent version of HOMM3 in Steam. Ah okay did not have understood what the RMG was for - atleast it doesn't ask for h3maped ... I was trying the German Version and also tryed English one, I did revalidate all files and even tryed to fresh install but all it says that HOMM3 2.0.exe stoped working... Any ideas of what I'm doing wrong?

Edit: Oh and all latest attempts were only on Windows.

**Comment by valepu** [comment]
I'm having this same issue. There's no h3maped in the HOMM3 folder and i have a fresh installation of the game (installed yesterday), there is a mapEditor.exe though.
I have tried making a copy of the editor and renaming it h3maped but then the game crashed

And i actually wanted to use the random map generator

**Comment by potmdehex** [comment]
@valepu, h3maped.exe comes with Heroes III Complete, you need to own that to integrate the random map generator in HD Edition with HDE Mod because otherwise there is no random map generator to integrate. 

@XIIIFaces If your game starts fine without HDE Mod most likely some third party software such as antivirus is causing it to crash.

**Comment by AaronM172** [comment]
what folder would the h3maped be in then? If bought through steam

**Comment by potmdehex** [comment]
@AaronM172, h3maped.exe does not come with the Steam version. See my answer to @valepu.

**Comment by AaronM172** [comment]
yes but where does it come from because i own the complete edition
