### ISSUE TITLE
Error on install on ubuntu

### ISSUE THREAD

**Issue by ghost** [potmdehex/homm3tools#47]
Hi,

I don't know if this is me being silly or something else, but I can't install properly.
Ubuntu 22.04.
Unzip source code of pre-built binary HDE Mod 1.22.
cd homm3tools/BUILD/gcc
in terminal: make
output is:

<pre>make -C ../../h3m/h3mtilespritegen/BUILD/gcc install
make[1]: Entering directory &apos;/-/homm3tools/h3m/h3mtilespritegen/BUILD/gcc&apos;
mkdir -p ../../../../OUTPUT/gcc
cp h3mtilespritegen.a ../../../../OUTPUT/gcc
cp h3mtilespritegen.so ../../../../OUTPUT/gcc
make[1]: Leaving directory &apos;/-/homm3tools/h3m/h3mtilespritegen/BUILD/gcc&apos;
make -C ../../h3m/h3mlib/BUILD/gcc install
make[1]: Entering directory &apos;/-/homm3tools/h3m/h3mlib/BUILD/gcc&apos;
cc ../../h3mlib.c -c -I ../../../../3rdparty/uthash/src -I ../../../h3mtilespritegen -std=c99 -DNO_ZLIB -O3 -Wall -Werror -Wno-unused -Wno-unused-result -Wno-strict-aliasing -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast -fPIC -o obj/h3mlib.o
In file included from <b>/usr/include/string.h:535</b>,
                 from <b>../../h3m_editing/../internal/../meta/../../../3rdparty/uthash/src/utarray.h:38</b>,
                 from <b>../../h3m_editing/../internal/../meta/h3mlib_meta.h:21</b>,
                 from <b>../../h3m_editing/../internal/h3mlib_ctx.h:8</b>,
                 from <b>../../h3m_editing/h3mlib_alg_od_text.h:6</b>,
                 from <b>../../h3mlib.c:8</b>:
In function ‘<b>strncpy</b>’,
    inlined from ‘<b>h3m_desc_set</b>’ at <b>../../h3mlib.c:1039:5</b>:
<b>/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10:</b> <font color="#C01C28"><b>error: </b></font>‘<b>__builtin_strncpy</b>’ output truncated before terminating nul copying as many bytes from a string as its length [<font color="#C01C28"><b>-Werror=stringop-truncation</b></font>]
   95 |   return <font color="#C01C28"><b>__builtin___strncpy_chk (__dest, __src, __len,</b></font>
      |          <font color="#C01C28"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
   96 | <font color="#C01C28"><b>                                  __glibc_objsize (__dest))</b></font>;
      |                                   <font color="#C01C28"><b>~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
<b>../../h3mlib.c:</b> In function ‘<b>h3m_desc_set</b>’:
<b>../../h3mlib.c:1036:16:</b> <font color="#2AA1B3"><b>note: </b></font>length computed here
 1036 |     size_t n = <font color="#2AA1B3"><b>strlen(desc)</b></font>;
      |                <font color="#2AA1B3"><b>^~~~~~~~~~~~</b></font>
cc1: all warnings being treated as errors
make[1]: *** [makefile:43: obj/h3mlib.o] Error 1
make[1]: Leaving directory &apos;/-/homm3tools/h3m/h3mlib/BUILD/gcc&apos;
make: *** [makefile:3: all] Error 2
</pre>

gcc version 11.2.0

Am I doing this wrong someway?

**Comment by potmdehex** [comment]
I suggest downloading and trying to build the latest source (https://github.com/potmdehex/homm3tools/archive/refs/heads/master.zip)

The last HDE Mod binary release from 2016 is behind master (and wasn't meant for anything general purpose, just HDE Mod for Windows specifically).

**Comment by ghost** [comment]
Cool, it worked! My miss.

Btw, is there a list of functionalities for homm3tools somewhere?

**Comment by potmdehex** [comment]
No, there is no such list. For h3mlib (the library for parsing and producing .h3m files for Heroes 3) the interface is defined in [h3mlib.h](https://github.com/potmdehex/homm3tools/blob/master/h3m/h3mlib/h3mlib.h) and there's some example usage in [h3mhelloworld.c](https://github.com/potmdehex/homm3tools/blob/master/h3m/h3mhelloworld/h3mhelloworld.c) (you will find the h3mhelloworld binary in the OUTPUT directory when you build homm3tools and if you execute it you will find the produced test.h3m in the same directory). 

Do you have any particular use case in mind?

**Comment by ghost** [comment]
Alright, great.

I've noticed that the complete edition has this functionality for swapping armies/artifacts between heroes, which would be neat. Might be a lot of work to implement though.

**Comment by potmdehex** [comment]
HDE Mod has that functionality implemented as hotkeys here: https://github.com/potmdehex/homm3tools/blob/master/hd_edition/hde_mod/mod/hero_trade.c

A list of the hotkeys is here: 
https://github.com/potmdehex/homm3tools/blob/6b36d1f92ea67f5ad6d4847aeaf2dfb1766d3cc5/hd_edition/hde_launcher_mod/guimod.cpp#L289

General HDE Mod features list (from Steam / HC post):
* HD Edition Random Map Generator integration (if you specify path to a H3 Complete installation, you can get integration of the RMG into HD Edition when you start new game)
* HD Edition Object Re-visit (re-visit objects with space bar like in AB/SoD)
* HD Edition Quick Combat Re-play (press Escape at Quick Combat battle result screen to re-play that battle without Quick Combat)
* HD Edition No Sound Delay (removes delay when e.g entering battles)
* HD Edition Extra Hotkeys (for swapping/moving all artifacts/creatures in hero trade screen)
* HD Edition 60 FPS (increases framerate to 60 FPS)
* HD Edition System Cursor fix (completely replace game's cursor rendering with lag-free system cursor. Ubisoft integrated this fix in Patch 3)
* HD Edition XXL Maps fix. Ability to play non-standard sized maps, e.g XXL 252x252

**Comment by ghost** [comment]
Ohh, yes, I forgot that list. My miss, again.

I tested most of them, and they work, except some:
Shift click - nothing happens, only normal click
Ctrl click - behaves as ctrl shift click 

Are these known issues? Couldn't find them in any issue.

**Comment by potmdehex** [comment]
Is that with when you build from master or using the pre-built binary? 

The hotkeys are implemented here: https://github.com/potmdehex/homm3tools/blob/master/hd_edition/hde_mod/mod/stack_split.c

If you are building, try using this stack_split.c, which is the last I personally tested (same as in pre-built binary): https://github.com/potmdehex/homm3tools/blob/7ce82f090e95d44e326cd942624adea169a65a65/hd_edition/hde_mod/mod/stack_split.c

If it does not work there is either a problem on your end or changes in Windows behavior which I am unaware of and cannot help with.

**Comment by ghost** [comment]
I've done it like this:
Extract content of [(https://github.com/potmdehex/homm3tools/archive/refs/heads/master.zip)](https://github.com/potmdehex/homm3tools/archive/refs/heads/master.zip)
into homm3 game folder.
Navigate to /homm3tools-master/BUILD/gcc
$ make

Is this the correct way? I'm quite new to both Github and Ubuntu, so its most likely a problem on my end.

**Comment by potmdehex** [comment]
That is the correct way to build homm3tools, but unless you want to make changes to the code you do not need to build at all.

HDE Mod is for HD Edition, if that is what you are running then you can just use hde_mod_installer.exe in https://github.com/potmdehex/homm3tools/releases/download/1.22/HDE.Mod.1.22.zip. 

If you are running HD Edition, you should have no problems with the shift key hotkeys after installing the above.

If you are running Heroes III Complete and not HD Edition, I suggest looking for other mods such as HD Mod by baratorch. homm3tools doesn't include mods for Heroes III Complete, only tools/libraries such as h3mlib.

**Comment by ghost** [comment]
Ohh, yeah, then I'm not going to build it.

I didn't get that installer to work before, hence the build, but now I realised that Wine wasn't showing hidden files. So the install was a success. However, I still have the same behaviour with ctrl + click. 

I am using HD edition (via Steam). 

I think I should do a re-install - is it best to just wipe everything or remove select files?

**Comment by potmdehex** [comment]
Wiping everything is a good idea. 

When HDE Mod is correctly installed and running, the launcher menu should look like this:

![](https://raw.githubusercontent.com/potmdehex/homm3tools/master/screenshots/hde_mod/hde_mod.png)

If it does not look like that for you, HDE Mod is not running. 

I cannot assist you with how to get it to work properly in Wine, it was never tested.

**Comment by ghost** [comment]
Wiped everything and reinstalled the same way. Still no luck.

My launcher looks like that, yes (with a newer mod version than in your pic):
![image](https://user-images.githubusercontent.com/106199841/192593010-12971996-5653-4b0a-b8af-234f1ae20180.png)

If not with wine, do you have any recommendation on installation-procedure in Ubuntu?

**Comment by potmdehex** [comment]
If you want to use mods, I would recommend playing the game on Windows or in a Windows VM. I would expect many mods of many games to not work in Wine, even if installed correctly.
